---
title: Code
---

The following list provides links to the code used in the guided coding sessions. The code will be added as the course progresses. The solutions to the challenges will be available on Blackboard.

<div class="panel-group">
<div class="panel panel-default">
<div class="panel-heading">
<h2 id="week-2" class="panel-title">
<a data-toggle="collapse" href="#collapse2">Week 2: 08/29. Webscraping.</a>
</h2>
</div>
<div id="collapse2" class="panel-collapse collapse in" style="margin:12px">

<ul>
<li><p><a href="slides/03-scraping.pdf">Slides: webscraping (.pdf file)</a></p>
</li>
<li><p><a href="code/00-setup.html">Introduction to RMarkdown</a> (<a href="code/00-setup.Rmd">.Rmd file</a>)</p>
</li>
<li><p><a href="code/01-scraping-tables.html">Scraping tables from websites</a> (<a href="code/01-scraping-tables.Rmd">.Rmd file</a>)</p>
</li>
<li><p><a href="code/02-scraping-unstructured-data.html">Scraping unstructured data</a> (<a href="code/02-scraping-unstructured-data.Rmd">.Rmd file</a>)</p>
</li>
<li><p><a href="challenges/challenge1.Rmd">Coding challenge 1 (.Rmd file)</a></p>
</li>
</ul>
</div>
</div>
</div>

<div class="panel-group">
<div class="panel panel-default">
<div class="panel-heading">
<h2 id="week-3" class="panel-title">
<a data-toggle="collapse" href="#collapse3">Week 3: 09/05. Survey research.</a>
</h2>
</div>
<div id="collapse3" class="panel-collapse collapse in" style="margin:12px">

<ul>
<li><p><a href="slides/04-multilevel.pdf">Slides: introduction to multilevel models (.pdf file)</a></p>
</li>
<li><p><a href="">Multilevel models with R</a> (See Blackboard for code)</p>
</li>
<li><p><a href="">Multilevel Regression and Poststratification</a> (See Blackboard for code)</p>
</li>
<li><p><a href="challenges/challenge2.Rmd">Coding challenge 2 (.Rmd file)</a></p>
</li>
</ul>
</div>
</div>
</div>



<div class="panel-group">
<div class="panel panel-default">
<div class="panel-heading">
<h2 id="week-4" class="panel-title">
<a data-toggle="collapse" href="#collapse4">Week 4: 09/12. Experiments.</a>
</h2>
</div>
<div id="collapse4" class="panel-collapse collapse in" style="margin:12px">

<ul>
<li><p><a href="slides/06-parallel.pdf">Slides: efficient data analysis with R (.pdf file)</a></p>
</li>

<li><p><a href="code/05-efficient-programming.html">Efficient programming with R</a> (<a href="code/05-efficient-programming.Rmd">.Rmd file</a>)</p>
</li>
<li><p><a href="code/06-parallel-computing.html">Parallel computing with R</a> (<a href="code/06-parallel-computing.Rmd">.Rmd file</a>)</p>
</li>
</li>
<li><p><a href="challenges/challenge3.Rmd">Coding challenge 3 (.Rmd file)</a></p>
</li>
</ul>
</div>
</div>
</div>



<div class="panel-group">
<div class="panel panel-default">
<div class="panel-heading">
<h2 id="week-5" class="panel-title">
<a data-toggle="collapse" href="#collapse5">Week 5: 09/19. Text (I).</a>
</h2>
</div>
<div id="collapse5" class="panel-collapse collapse in" style="margin:12px">

<ul>

<li><p><a href="code/07-text-intro.html">Basics of text analysis with R</a> (<a href="code/07-text-intro.Rmd">.Rmd file</a>)</p>
</li>
<li><p><a href="code/08-dictionary-methods.html">Dictionary methods applied to sentiment analysis</a> (<a href="code/08-dictionary-methods.Rmd">.Rmd file</a>)</p>
</li>
<li><p><a href="challenges/challenge4.Rmd">Coding challenge 4 (.Rmd file)</a></p>
</li>
</ul>
</div>
</div>
</div>


<div class="panel-group">
<div class="panel panel-default">
<div class="panel-heading">
<h2 id="week-6" class="panel-title">
<a data-toggle="collapse" href="#collapse6">Week 6: 09/26. Text (II).</a>
</h2>
</div>
<div id="collapse6" class="panel-collapse collapse in" style="margin:12px">

<ul>
<li><p><a href="code/09-supervised-learning.html">Supervised learning applied to text classification</a> (<a href="code/09-supervised-learning.Rmd">.Rmd file</a>)</p>
</li>
<li><p><a href="code/10-encoding-issues.html">Encoding issues when working with text</a> (<a href="code/10-encoding-issues.Rmd">.Rmd file</a>)</p>
</li>
<li><p><a href="challenges/challenge5.Rmd">Coding challenge 5</a></p>
</li>
</ul>
</div>
</div>
</div>


<div class="panel-group">
<div class="panel panel-default">
<div class="panel-heading">
<h2 id="week-7" class="panel-title">
<a data-toggle="collapse" href="#collapse7">Week 7: 10/03. Text (III).</a>
</h2>
</div>
<div id="collapse1" class="panel-collapse collapse in" style="margin:12px">


<ul>
<li><p><a href="code/11-text-discovery.html">Exploring large-scale text datasets</a> (<a href="code/11-text-discovery.Rmd">.Rmd file</a>)</p>
</li>
<li><p><a href="code/12-topic-models.html">Topic models</a> (<a href="code/12-topic-models.Rmd">.Rmd file</a>)</p>
</li>
<li><p><a href="challenges/challenge6.Rmd">Coding challenge 6</a></p>
</li>
</ul>
</div>
</div>
</div>

<div class="panel-group">
<div class="panel panel-default">
<div class="panel-heading">
<h2 id="week-8" class="panel-title">
<a data-toggle="collapse" href="#collapse8">Week 8: 10/10. Text (IV).</a>
</h2>
</div>
<div id="collapse8" class="panel-collapse collapse in" style="margin:12px">


<ul>
<li><p><a href="code/13-word-embeddings.html">Introduction to word2vec</a> (<a href="code/13-word-embeddings.Rmd">.Rmd file</a>)</p>
</li>
<li><p><a href="code/14-ideological-scaling.html">Ideological scaling</a> (<a href="code/14-ideological-scaling.Rmd">.Rmd file</a>)</p>
</li>
<li><p><a href="challenges/challenge7.Rmd">Coding challenge 7</a></p>
</li>
</ul>
</div>
</div>
</div>


<div class="panel-group">
<div class="panel panel-default">
<div class="panel-heading">
<h2 id="week-9" class="panel-title">
<a data-toggle="collapse" href="#collapse9">Week 9: 10/17. Networks (I).</a>
</h2>
</div>
<div id="collapse9" class="panel-collapse collapse in" style="margin:12px">


<ul>
<li><p><a href="code/15-networks-intro-visualization.html">Introduction social network analysis with igraph</a> (<a href="code/15-networks-intro-visualization.Rmd">.Rmd file</a>)</p>
</li>
<li><p><a href="code/16-networks-descriptive-analysis.html">Descriptive analysis of social network datasets</a> (<a href="code/16-networks-descriptive-analysis.Rmd">.Rmd file</a>)</p>
</li>
<li><p><a href="challenges/challenge8.Rmd">Coding challenge 8</a></p>
</li>
</ul>
</div>
</div>
</div>


<div class="panel-group">
<div class="panel panel-default">
<div class="panel-heading">
<h2 id="week-10" class="panel-title">
<a data-toggle="collapse" href="#collapse10">Week 10: 10/24. Networks (II).</a>
</h2>
</div>
<div id="collapse10" class="panel-collapse collapse in" style="margin:12px">


<ul>
<li><p><a href="slides/12-networks-contagion.pdf">Slides: collecting social media data (.pdf file)</a></p>
</li>
<li><p><a href="code/17-twitter-streaming-data-collection.html">Collecting Twitter data from the Streaming API</a> (<a href="code/17-twitter-streaming-data-collection.Rmd">.Rmd file</a>)</p>
</li>
<li><p><a href="code/18-twitter-REST-data-collection.html">Collecting Twitter data from the REST API</a> (<a href="code/18-twitter-REST-data-collection.Rmd">.Rmd file</a>)</p>
</li>
<li><p><a href="code/19-facebook-data-collection.html">Collecting Facebook data from the Graph API</a> (<a href="code/19-facebook-data-collection.Rmd">.Rmd file</a>)</p>
</li>
<li><p><a href="challenges/challenge9.Rmd">Coding challenge 9</a></p>
</li>
</ul>
</div>
</div>
</div>



<div class="panel-group">
<div class="panel panel-default">
<div class="panel-heading">
<h2 id="week-11" class="panel-title">
<a data-toggle="collapse" href="#collapse11">Week 11: 10/31. Networks (III).</a>
</h2>
</div>
<div id="collapse11" class="panel-collapse collapse in" style="margin:12px">


<ul>
<li><p><a href="code/20-community-detection.html">Community detection methods</a> (<a href="code/20-community-detection.Rmd">.Rmd file</a>)</p>
</li>
<li><p><a href="code/21-latent-space.html">Latent space network models</a> (<a href="code/21-latent-space.Rmd">.Rmd file</a>)</p>
</li>
<li><p><a href="challenges/challenge10.Rmd">Coding challenge 10</a></p>
</li>
<li><p><a href="challenges/challenge11.Rmd">Coding challenge 11</a></p>
</li>
</ul>
</div>
</div>
</div>


<div class="panel-group">
<div class="panel panel-default">
<div class="panel-heading">
<h2 id="week-12" class="panel-title">
<a data-toggle="collapse" href="#collapse12">Week 12: 11/07. Spatial statistics.</a>
</h2>
</div>
<div id="collapse12" class="panel-collapse collapse in" style="margin:12px">


<ul>
<li><p><a href="">Working with shape files in R</a>. Materials based on Bivand, R. S., Pebesma, E., & Gómez-Rubio, V. (2013). <a href="http://usc.summon.serialssolutions.com/#!/search?bookMark=ePnHCXMw42JgAfZbU5lBe6iARb856Dx20BgbsGIG3YhiwgEbAAHNwAFTDyeDCrS9pVAMWkOcmKMAWhupkAg9k0MBNB6pEMTNoODmGuLsoVtanBwP2SIIrSKK40EdKkvQziGCSgBvtSyc">Applied Spatial Data Analysis with R</a>. Springer.</p>
</li>
<li><p><a href="">Spatial autoregression</a></p>
</li>
<li><p><a href="">Coding challenge 11</a></p>
</li>
</ul>
</div>
</div>
</div>


<div class="panel-group">
<div class="panel panel-default">
<div class="panel-heading">
<h2 id="week-13" class="panel-title">
<a data-toggle="collapse" href="#collapse13">Week 13: 11/14. Audiovisual data.</a>
</h2>
</div>
<div id="collapse13" class="panel-collapse collapse in" style="margin:12px">

<ul>
<li><p><a href="">Image classification with R</a></p>
</li>
<li><p><a href="">Coding challenge 12</a></p>
</li>
</ul>
</div>
</div>
</div>
