---
title: Course outline and readings
---

<div class="panel-group">
<div class="panel panel-default">
<div class="panel-heading">

<h2 id="week-1" class="panel-title">
<a data-toggle="collapse" href="#collapse1">Week 1: 08/28. Introduction</a>
</h2>
</div>
<div id="collapse1" class="panel-collapse collapse in" style="margin:12px">
<p><b>Topics:</b> Introductions and course overview. What is Computational Social Science? Good computing practices. Introduction to version control and GitHub</p>
<p><a href="slides/01-intro.pdf">SLIDES (.pdf): Introduction to the course.</a></p>
<h4>Background reading</h4>
<ul>
<li><p>Lazer, D., Pentland, A. S., Adamic, L., Aral, S., Barabasi, A. L., Brewer, D., ... & Jebara, T. (2009). <a href="http://fowler.ucsd.edu/computational_social_science.pdf">Life in the network: the coming age of computational social science</a>. <i>Science</i>, 323(5915), 721-3.</p>
</li>
<li><p>Golder, S. A., & Macy, M. W. (2014). <a href="http://www.annualreviews.org/doi/full/10.1146/annurev-soc-071913-043145">Digital footprints: Opportunities and challenges for online social research.</a> <i>Annual Review of Sociology</i>, 40(1), 129.</p>
</li>
<li><p>Grimmer, J. (2015). <a href="https://www.cambridge.org/core/services/aop-cambridge-core/content/view/S1049096514001784">We are all social scientists now: how big data, machine learning, and causal inference work together</a>. <i>PS: Political Science & Politics</i>, 48(1), 80-83.</p>
</li>
<li><p>Nagler, J. (1995). <a href="http://www.jstor.org/stable/420315">Coding style and good computing practices</a>. <i>PS: Political Science & Politics</i>, 28(3), 488-492.</p>
</li>
</ul>
</div>
</div>
</div>


<div class="panel-group">
<div class="panel panel-default">
<div class="panel-heading">
<h2 id="week-2" class="panel-title">
<a data-toggle="collapse" href="#collapse2">Week 2: 09/04. Ethics.</a>
</h2>
</div>
<div id="collapse2" class="panel-collapse collapse in" style="margin:12px">

<p><b>Topics:</b> Computational social science: research opportunities and challenges. Ethics of social science research in the digital age. Big data, big bias? Data collection: automated data collection from the web.</p>

<p><a href="slides/02-big-data.pdf">SLIDES (.pdf): Computational Social Science - Research opportunities and challenges.</a></p>

<h4>Background reading</h4>
<ul>
<li><p>Barberá, P. & and Steinert-Threlkeld, Z. (2017). <a href="http://pablobarbera.com/static/social-media-data-generators.pdf">How to Use Social Media Data for Political Science Research.</a> Forthcoming in Curini, L., and Franzese, R. (eds) <i>The SAGE Handbook of Research Methods in Political Science and International Relations</i>, London: Sage, 2019.</p>
</li>
<li><p>Lazer, D. & and Radford, J. (2017). <a href="http://www.annualreviews.org/doi/abs/10.1146/annurev-soc-060116-053457">Data ex Machina: Introduction to Big Data.</a> <i>Annual Review of Sociology</i>.</p>
</li>
<li><p><a href="http://www.bitbybitbook.com/en/ethics/">Chapter 6</a> of Salganik, M. (2017). <a href="http://www.bitbybitbook.com/">Bit by Bit: Social Research in the Digital Age.</a> Princeton, NJ: Princeton University Press. Open review edition.</p>
</li>
</ul>

<h4>Readings for discussion</h4>
<ul>
<li><p>Kramer, A. D., Guillory, J. E., & Hancock, J. T. (2014). <a href="http://www.pnas.org/content/111/24/8788.short">Experimental evidence of massive-scale emotional contagion through social networks.</a> <i>Proceedings of the National Academy of Sciences</i>, 111(24), 8788-8790.<p>
</li>

</ul>

</div>
</div>
</div>

<div class="panel-group">
<div class="panel panel-default">
<div class="panel-heading">
<h2 id="week-3" class="panel-title">
<a data-toggle="collapse" href="#collapse3">Week 3: 09/11. Online experiments.</a>
</h2>
</div>
<div id="collapse3" class="panel-collapse collapse in" style="margin:12px">

<p><b>Topics:</b> Large-scale online experiments. Parallel programming with R.</p>

<p><a href="slides/05-experiments.pdf">SLIDES (.pdf): Experimental research in the digital age.</a></p>

<h4>Background reading</h4>
<ul>
<li><p>Chen, Y., & Konstan, J. (2015). <a href="https://link.springer.com/article/10.1007/s40881-015-0005-3">Online field experiments: a selective survey of methods.</a> <i>Journal of the Economic Science Association</i>, 1(1), 29-42.<p>
</li>
</ul>

<h4>Readings for discussion</h4>
<ul>
<li><p>Bond, R. M., Fariss, C. J., Jones, J. J., Kramer, A. D., Marlow, C., Settle, J. E., & Fowler, J. H. (2012). <a href="https://www.nature.com/nature/journal/v489/n7415/abs/nature11421.html">A 61-million-person experiment in social influence and political mobilization.</a> <i>Nature</i>, 489(7415), 295-298.</p>
</li>
<li><p>King, G., Pan, J., & Roberts, M. E. (2014). <a href="http://scholar.harvard.edu/files/gking/files/experiment_0.pdf">Reverse-engineering censorship in China: Randomized experimentation and participant observation</a>. <i>Science</i>, 345(6199), 1251722.</p>
</li>
<li><p>Munger, K. (2017). <a href="https://link.springer.com/article/10.1007/s11109-016-9373-5">Tweetment Effects on the Tweeted: An Experiment to Decrease Online Harassment.</a> <i>Political Behavior</i>, 39(3), 629-649.</p>
</li>
<li><p>Bail et al (2018). <a href="https://www.pnas.org/content/pnas/115/37/9216.full.pdf">Exposure to opposing views on social media can increase political polarization</a>. <i>Proceedings of the National Academy of Sciences</i>, 115(37): 9216-9221.</p>
</li>
</ul>

</div>
</div>
</div>


<div class="panel-group">
<div class="panel panel-default">
<div class="panel-heading">
<h2 id="week-4" class="panel-title">
<a data-toggle="collapse" href="#collapse4">Week 4: 09/18. Text (I).</a>
</h2>
</div>
<div id="collapse4" class="panel-collapse collapse in" style="margin:12px">

<p><b>Topics:</b> Introduction to automated text analysis. Sources of textual data. String manipulation in R. Regular expressions. Text processing with quanteda.</p>

<p><a href="slides/06-text-intro.pdf">SLIDES (.pdf): Introduction to automated text analysis. Text preprocessing.</a></p>


<h4>Background reading</h4>
<ul>
<li><p>Grimmer, J., & Stewart, B. M. (2013). <a href="https://www.cambridge.org/core/journals/political-analysis/article/div-classtitletext-as-data-the-promise-and-pitfalls-of-automatic-content-analysis-methods-for-political-textsdiv/F7AAC8B2909441603FEB25C156448F20">Text as data: The promise and pitfalls of automatic content analysis methods for political texts</a>. <i>Political analysis</i>, 21(3), 267-297.<p>
</li>
<li><p>Benoit, K. (2019). <a href="https://kenbenoit.net/pdfs/28%20Benoit%20Text%20as%20Data%20draft%202.pdf">Text as data: an overview.</a> Forthcoming in Curini, L., and Franzese, R. (eds) <i>The SAGE Handbook of Research Methods in Political Science and International Relations</i>, London: Sage, 2019.</p>
</li>
<li><p>Wilkerson, J. and Casas, A. (2017). <a href="https://www.annualreviews.org/doi/abs/10.1146/annurev-polisci-052615-025542?journalCode=polisci">Large-Scale Computerized Text Analysis in Political Science: Opportunities and Challenges.</a> <i>Annual Review of Political Science</i>, 20, 529:544.</p>
</li>
<li><p>Denny, M. J., & Spirling, A. (2018). <a href="https://www.cambridge.org/core/journals/political-analysis/article/text-preprocessing-for-unsupervised-learning-why-it-matters-when-it-misleads-and-what-to-do-about-it/AA7D4DE0AA6AB208502515AE3EC6989E">Text preprocessing for unsupervised learning: why it matters, when it misleads, and what to do about it.</a> <i>Political Analysis</i>, 26(2): 168-189.</p>
</li>
</ul>

<h4>No readings for discussion this week</h4>


</div>
</div>
</div>



<div class="panel-group">
<div class="panel panel-default">
<div class="panel-heading">
<h2 id="week-5" class="panel-title">
<a data-toggle="collapse" href="#collapse5">Week 5: 09/25. Text (II).</a>
</h2>
</div>
<div id="collapse5" class="panel-collapse collapse in" style="margin:12px">

<p><b>Topics:</b> Dictionary methods applied to sentiment analysis.</p>

<p><a href="slides/07-dictionaries.pdf">SLIDES (.pdf): Dictionary methods.</a></p>


<h4>Background reading</h4>
<ul>
<li><p>González-Bailón, S., & Paltoglou, G. (2015). <a href="https://journals.sagepub.com/doi/pdf/10.1177/0002716215569192?casa_token=a0RzWG5Ax84AAAAA:1Bz3VYxGncl41uzHDY8GAiQiXUJN10ExZGtpDuu2n-qxPwI20hn-l-omjrI5SkwB8X8ToB-6K1M_">Signals of public opinion in online communication: A comparison of methods and data sources.</a>. <i>The ANNALS of the American Academy of Political and Social Science</i>, 659(1), 95-107.</p>
</li>
<li><p>Barberá et al (2019). <a href="http://www.pablobarbera.com/static/text_practical_guide.pdf">Automated Text Classification of News Articles: A Practical Guide.</a> <i>Working paper</i>.

</li>	
</ul>

<h4>Readings for discussion</h4>
<ul>
<li><p>Young, L., & Soroka, S. (2012). <a href="http://www.tandfonline.com/doi/abs/10.1080/10584609.2012.671234">Affective news: The automated coding of sentiment in political texts</a>. <i>Political Communication</i>, 29(2), 205-231.</p>
</li>
<li><p>Tausczik, Y. R., & Pennebaker, J. W. (2010). <a href="http://journals.sagepub.com/doi/abs/10.1177/0261927X09351676">The psychological meaning of words: LIWC and computerized text analysis methods</a>. <i>Journal of language and social psychology</i>, 29(1), 24-54.</p></li>
</ul>

</div>
</div>
</div>


<div class="panel-group">
<div class="panel panel-default">
<div class="panel-heading">
<h2 id="week-6" class="panel-title">
<a data-toggle="collapse" href="#collapse6">Week 6: 10/02. Text (III).</a>
</h2>
</div>
<div id="collapse6" class="panel-collapse collapse in" style="margin:12px">

<p><b>Topics:</b> Supervised machine learning applied to text classification. Crowd-sourcing the creation of training datasets.</p>

<p><a href="slides/08-supervised-learning.pdf">SLIDES (.pdf): Introduction to supervised learning applied to text classification.</a></p>

<h4>Background reading</h4>
<ul>
<li><p>Chapters 1, 3, and 5 of James, G., Witten, D., Hastie, T., & Tibshirani, R. (2013). <a href="https://library.usc.edu/uhtbin/cgisirsi/x/0/0/57/5/3?searchdata1=4192313{CKEY}&searchfield1=GENERAL^SUBJECT^GENERAL^^&user_id=WEBSERVER">An introduction to statistical learning.</a> New York: Springer.</p>
</li>
<li><p>Benoit, K., Conway, D., Lauderdale, B. E., Laver, M., & Mikhaylov, S. (2016). <a href="https://www.cambridge.org/core/journals/american-political-science-review/article/crowd-sourced-text-analysis-reproducible-and-agile-production-of-political-data/EC674A9384A19CFA357BC2B525461AC3">Crowd-sourced text analysis: reproducible and agile production of political data</a>. <i>American Political Science Review</i>, 110(2), 278-295.</p>
</li>
</ul>

<h4>Readings for discussion</h4>
<ul>
<li><p>Beauchamp, N. (2017). <a href="http://onlinelibrary.wiley.com/doi/10.1111/ajps.12274/full">Predicting and Interpolating State‐Level Polls Using Twitter Textual Data</a>. American Journal of Political Science, 61(2), 490-503.</p>
</li>
<li><p>Theocharis, Y., Barberá, P., Fazekas, Z., Popa, S. A. and Parnet, O. (2016). <a href="http://onlinelibrary.wiley.com/doi/10.1111/jcom.12259/abstract">A Bad Workman Blames His Tweets: The Consequences of Citizens' Uncivil Twitter Use When Interacting With Party Candidates</a>. <i>Journal of Communication</i>, 66: 1007–1031.</p>
</li>
<li>Davidson et al. (2017). <a href="https://aaai.org/ocs/index.php/ICWSM/ICWSM17/paper/view/15665/14843">Automated Hate Speech Detection and the Problem of Offensive Language</a>. ICWSM 2017.
</ul>

</div>
</div>
</div>


<div class="panel-group">
<div class="panel panel-default">
<div class="panel-heading">
<h2 id="week-7" class="panel-title">
<a data-toggle="collapse" href="#collapse7">Week 7: 10/09. Text (IV).</a>
</h2>
</div>
<div id="collapse1" class="panel-collapse collapse in" style="margin:12px">

<p><b>Topics:</b> Unsupervised machine learning (topic models).</p>

<p><a href="slides/09-topic-models.pdf">SLIDES (.pdf): Introduction to unsupervised machine learning. Topic models.</a></p>

<h4>Background reading</h4>
<ul>
<li><p>Blei, D. M. (2012). <a href="http://dl.acm.org/citation.cfm?id=2133826">Probabilistic topic models.</a> <i>Communications of the ACM</i>, 55(4), 77-84.</p>
</li>
<li><p>Roberts, M. E., Stewart, B. M., Tingley, D., Lucas, C., Leder‐Luis, J., Gadarian, S. K., ... & Rand, D. G. (2014). <a href="http://authors.library.caltech.edu/52278/7/topicmodelsopenendedexperiments.pdf">Structural Topic Models for Open‐Ended Survey Responses.</a> <i>American Journal of Political Science</i>, 58(4), 1064-1082.</p>
</li>
</ul>

<h4>Readings for discussion</h4>
<ul>
<li><p>Barberá et al. (2019). <a href="https://www.cambridge.org/core/journals/american-political-science-review/article/who-leads-who-follows-measuring-issue-attention-and-agenda-setting-by-legislators-and-the-mass-public-using-social-media-data/D855849CE288A241529E9EC2E4FBD3A8">Who Leads? Who Follows? Measuring Issue Attention and Agenda Setting by Legislators and the Mass Public Using Social Media Data.</a> <i>American Political Science Review</i></p></li>
<li><p>de Vries, E., Schoonvelde, M. & Schumacher, G. (2018). <a href="https://www.cambridge.org/core/journals/political-analysis/article/no-longer-lost-in-translation-evidence-that-google-translate-works-for-comparative-bagofwords-text-applications/43CB03805973BB8AD567F7AE50E72CA6">No Longer Lost in Translation: Evidence that Google Translate Works for Comparative Bag-of-Words Text Applications</a>. <i>Political Analysis</i>, 26(4), 417-430.</p>
</li>
</ul>

</div>
</div>
</div>

<div class="panel-group">
<div class="panel panel-default">
<div class="panel-heading">
<h2 id="week-8" class="panel-title">
<a data-toggle="collapse" href="#collapse8">Week 8: 10/16. Text (V).</a>
</h2>
</div>
<div id="collapse8" class="panel-collapse collapse in" style="margin:12px">

<p><b>Topics:</b> Ideological scaling of documents. Event detection. Introduction to word embeddings.</p>

<p><a href="slides/10-advanced-text.pdf">SLIDES (.pdf): Advanced automated text analysis.</a></p>

<h4>Background reading</h4>
<ul>
<li><p>Lowe, W. (2008). <a href="http://www.jstor.org/stable/25791945">Understanding wordscores</a>. <i>Political Analysis</i>, 16(4), 356-371.</p>

</li>
<li><p>Beieler, J., Brandt, P. T., Halterman, A., Schrodt, P. A., & Simpson, E. M. (2016). Generating political event data in near real time, in Alvarez, M. (ed.) Computational Social Science. Cambridge: Cambridge University Press. [<a href="https://library.usc.edu/uhtbin/cgisirsi/x/0/0/57/5/3?searchdata1=5096841{CKEY}&searchfield1=GENERAL^SUBJECT^GENERAL^^&user_id=WEBSERVER">Full text available through USC libraries</a>]</p>
</li>
<li><p>Skim: Mikolov, T., Chen, K., Corrado, G., & Dean, J. (2013). <a href="https://arxiv.org/pdf/1301.3781.pdf">Efficient estimation of word representations in vector space.</a> arXiv preprint arXiv:1301.3781.</p>
</li>
<li><p>Skim: Spirling, A. and Rodriguez, P. (2019). <a href="https://www.nyu.edu/projects/spirling/documents/embed.pdf">Word Embeddings
What works, what doesn’t, and how to tell the difference for applied research</a>. Working paper, New York University</p>
</li>
</ul>

<h4>Readings for discussion</h4>
<ul>
<li><p>Rodman, E. (2019). <a href="https://www.cambridge.org/core/journals/political-analysis/article/timely-intervention-tracking-the-changing-meanings-of-political-concepts-with-word-vectors/DDF3B5833A12E673EEE24FBD9798679E">A Timely Intervention: Tracking the Changing Meanings of Political Concepts with Word Vectors.</a> <i>Political Analysis</i>.</p>
</li>
<li><p>Rheault, L and Cochrane, C. (2019). <a href="https://www.cambridge.org/core/journals/political-analysis/article/word-embeddings-for-the-analysis-of-ideological-placement-in-parliamentary-corpora/017F0CEA9B3DB6E1B94AC36A509A8A7B">Word Embeddings for the Analysis of Ideological Placement in Parliamentary Corpora.</a> <i>Political Analysis</i>.</p>
</li>

</ul>

</div>
</div>
</div>


<div class="panel-group">
<div class="panel panel-default">
<div class="panel-heading">
<h2 id="week-9" class="panel-title">
<a data-toggle="collapse" href="#collapse9">Week 9: 10/23. Networks (I).</a>
</h2>
</div>
<div id="collapse9" class="panel-collapse collapse in" style="margin:12px">

<p><b>Topics:</b> Basic concepts in social network analysis. Network visualization.</p>

<p><a href="slides/11-networks-intro.pdf">SLIDES (.pdf): Introduction to social network analysis.</a></p>

<h4>Background reading</h4>
<ul>
<li><p>Sinclair, B. (2016). Network Structure and Social Outcomes: Network Analysis for Social Science, in Alvarez, M. (ed.) Computational Social Science. Cambridge: Cambridge University Press. [<a href="https://library.usc.edu/uhtbin/cgisirsi/x/0/0/57/5/3?searchdata1=5096841{CKEY}&searchfield1=GENERAL^SUBJECT^GENERAL^^&user_id=WEBSERVER">Full text available through USC libraries</a>]
</li>
<li><p>Chapters 1, 2, and 3 in Easley, D., & Kleinberg, J. (2010). <a href="https://www.cs.cornell.edu/home/kleinber/networks-book/">Networks, crowds, and markets</a>. Cambridge University Press.<p>
</li>
</ul>

<h4>Readings for discussion</h4>
<ul>
<li><p>Iakhnis, E. and Badawy, A. (2019). <a href="https://arxiv.org/abs/1907.11283">Networks of Power: Analyzing World Leaders Interactions on Social Media</a>. <i>arXiv prepring</i>, 1907.11283.</p>
</li>
<li><p>Bisbee, J., & Larson, J. M. (2017). <a href="https://www.cambridge.org/core/journals/american-political-science-review/article/testing-social-science-network-theories-with-online-network-data-an-evaluation-of-external-validity/4BF517F10F38DFB574FED4A3D805B613">Testing Social Science Network Theories with Online Network Data: An Evaluation of External Validity.</a> <i>American Political Science Review</i>, 1-20.</p>
</li>
</ul>

</div>
</div>
</div>


<div class="panel-group">
<div class="panel panel-default">
<div class="panel-heading">
<h2 id="week-10" class="panel-title">
<a data-toggle="collapse" href="#collapse10">Week 10: 10/30. Networks (II).</a>
</h2>
</div>
<div id="collapse10" class="panel-collapse collapse in" style="margin:12px">

<p><b>Topics:</b> Social contagion processes: homophily vs influence. Collecting social media data.</p>

<h4>Background reading</h4>
<ul>
<li><p>McPherson, M., Smith-Lovin, L., & Cook, J. M. (2001). <a href="http://www.annualreviews.org/doi/abs/10.1146/annurev.soc.27.1.415">Birds of a feather: Homophily in social networks.</a> <i>Annual review of sociology</i>, 27(1), 415-444.</p>
</li>
</ul>

<h4>Readings for discussion</h4>
<ul>
<li><p>Christakis, N. A., & Fowler, J. H. (2007). <a href="http://www.nejm.org/doi/full/10.1056/NEJMsa066082#t=article">The spread of obesity in a large social network over 32 years</a>. <i>New England Journal of Medicine</i>, 357, 370-379.</p>
</li>
<li><p>Centola, D. (2010). <a href="http://science.sciencemag.org/content/329/5996/1194">The spread of behavior in an online social network experiment</a>. <i>Science</i>, 329 (5996), 1194-1197.</p>
</li>
<li><p>Aral, S., Muchnik, L., & Sundararajan, A. (2009). <a href="http://www.pnas.org/content/106/51/21544.short">Distinguishing influence-based contagion from homophily-driven diffusion in dynamic networks.</a> <i>Proceedings of the National Academy of Sciences</i>, 106(51), 21544-21549.</p>
</li>
</ul>

</div>
</div>
</div>



<div class="panel-group">
<div class="panel panel-default">
<div class="panel-heading">
<h2 id="week-11" class="panel-title">
<a data-toggle="collapse" href="#collapse11">Week 11: 11/06. SQL.</a>
</h2>
</div>
<div id="collapse11" class="panel-collapse collapse in" style="margin:12px">

<p><b>Topics:</b> Querying large-scale online datasets with SQL and Google BigQuery.</p>

<p><a href="slides/12-SQL.pdf">SLIDES (.pdf): SQL and Google BigQuery.</a></p>

<h4>Background reading</h4>
<ul>
<li><p>Beaulieu, A. (2009). <a href="https://books.google.co.uk/books?hl=en&lr=&id=1PgCCVryjOQC&oi=fnd&pg=PR3&dq=learning+sql+alan&ots=X6M3Iaz1wO&sig=38Fp1kDlxM8TF7miw0K2CNcKib4#v=onepage&q=learning%20sql%20alan&f=false">Learning SQL: Master SQL Fundamentals.</a> O'Reilly Media, Inc.</p></li>
<li><p>Stephens, R., Plew, R., & Jones, A. D. (2009). <a href="https://books.google.co.uk/books?hl=en&lr=&id=9fDZ_rVoxx0C&oi=fnd&pg=PR5&dq=%22Sams+Teach+Yourself+SQL+in+24+Hours%22&ots=UkaClJDMem&sig=wgLy-DG3bc7g0LO0_Ojy5Cy2Ejs#v=onepage&q=%22Sams%20Teach%20Yourself%20SQL%20in%2024%20Hours%22&f=false">Sams teach yourself SQL in one hour a day</a>. Sams Publishing.</p></li>
<li><p><a href="https://cloud.google.com/bigquery/docs/reference/legacy-sql">Google BigQuery: Legacy SQL Functions and Operators.</a></p></li>
</ul>


</div>
</div>
</div>


<div class="panel-group">
<div class="panel panel-default">
<div class="panel-heading">
<h2 id="week-12" class="panel-title">
<a data-toggle="collapse" href="#collapse12">Week 12: 11/13. Networks (III).</a>
</h2>
</div>
<div id="collapse12" class="panel-collapse collapse in" style="margin:12px">

<p><b>Topics:</b> Latent variable models. Introduction to exponential random graph models.</p>

<p><a href="slides/13-networks-latent.pdf">SLIDES (.pdf): Latent space network models. Community detection.</a></p>

<h4>Background reading</h4>
<ul>
<li><p>Robins, G., Pattison, P., Kalish, Y., & Lusher, D. (2007). <a href="http://www.sciencedirect.com/science/article/pii/S0378873306000372">An introduction to exponential random graph (p*) models for social networks.</a> <i>Social networks</i>, 29(2), 173-191.</p>
</li>
</ul>

<h4>Readings for discussion</h4>
<ul>
<li><p>Treier, S., & Jackman, S. (2008). <a href="http://onlinelibrary.wiley.com/doi/10.1111/j.1540-5907.2007.00308.x/full">Democracy as a latent variable.</a> American Journal of Political Science, 52(1), 201-217.</p>
</li>
<li><p>Barberá, P. (2014). <a href="https://www.cambridge.org/core/journals/political-analysis/article/div-classtitlebirds-of-the-same-feather-tweet-together-bayesian-ideal-point-estimation-using-twitter-datadiv/91E37205F69AEA32EF27F12563DC2A0A">Birds of the same feather tweet together: Bayesian ideal point estimation using Twitter data.</a> <i>Political Analysis</i>, 23(1), 76-91.</p>
</li>
<li><p>Cranmer, S. J., Menninga, E. J., & Mucha, P. J. (2015). <a href="http://www.pnas.org/content/112/38/11812.short">Kantian fractionalization predicts the conflict propensity of the international system</a>. <i>Proceedings of the National Academy of Sciences</i>, 112(38), 11812-11816.
</p></li>
</ul>


</div>
</div>
</div>


<div class="panel-group">
<div class="panel panel-default">
<div class="panel-heading">
<h2 id="week-13" class="panel-title">
<a data-toggle="collapse" href="#collapse13">Week 13: 11/20. Survey research.</a>
</h2>
</div>
<div id="collapse13" class="panel-collapse collapse in" style="margin:12px">

<p><b>Topics:</b> Recent advances in survey research. Multilevel regression and poststratification.</p>

<h4>Readings for discussion</h4>
<ul>
<li><p>Wang, W., Rothschild, D., Goel, S., & Gelman, A. (2015). <a href="http://stat.columbia.edu/~gelman/research/published/forecasting-with-nonrepresentative-polls.pdf">Forecasting elections with non-representative polls.</a> <i>International Journal of Forecasting</i>, 31(3), 980-991.<p>
</li>
<li><p>Jäger, K. (2017). <a href="https://www.cambridge.org/core/journals/political-analysis/article/potential-of-online-sampling-for-studying-political-activists-around-the-world-and-across-time/8F6159C4242EA2F443E2B0DACC0DA9F0">The potential of online sampling for studying political activists around the world and across time</a>. <i>Political Analysis</i>, 1-15.</p></li>
<li><p>Mullinix, K. J., Leeper, T. J., Druckman, J. N., & Freese, J. (2015). <a href="https://www.cambridge.org/core/journals/journal-of-experimental-political-science/article/the-generalizability-of-survey-experiments/72D4E3DB90569AD7F2D469E9DF3A94CB">The generalizability of survey experiments.</a> <i>Journal of Experimental Political Science</i>, 2(2), 109-138.<p>
</li>
<li><p>Muñoz, J., Falcó-Gimeno, A., and Hernández, E. (2019). <a href="https://www.cambridge.org/core/journals/political-analysis/article/unexpected-event-during-survey-design-promise-and-pitfalls-for-causal-inference/E9DB24A62172D1EB2116FEFFEAE45998">Unexpected Event during Survey Design: Promise and Pitfalls for Causal Inference</a>. <i>Political Analysis</i>, forthcoming.</p>
</li>
</ul>


</div>
</div>
</div>


<div class="panel-group">
<div class="panel panel-default">
<div class="panel-heading">
<h2 id="week-14" class="panel-title">
<a data-toggle="collapse" href="#collapse14">Week 14: 11/27. No class.</a>
</h2>
</div>
<div id="collapse14" class="panel-collapse collapse in" style="margin:12px">

<p>No class: Thanksgiving Holiday.</p>

</div>
</div>
</div>


<div class="panel-group">
<div class="panel panel-default">
<div class="panel-heading">
<h2 id="week-15" class="panel-title">
<a data-toggle="collapse" href="#collapse15">Week 15: 12/03. Presentations.</a>
</h2>
</div>
<div id="collapse15" class="panel-collapse collapse in" style="margin:12px">

<p>Student presentations of research projects. Course recap.</p>

</div>
</div>
</div>



<div class="panel-group">
<div class="panel panel-default">
<div class="panel-heading">
<h2 id="others" class="panel-title">
<a data-toggle="collapse" href="#others">Other topics.</a>
</h2>
</div>
<div id="others" class="panel-collapse collapse in" style="margin:12px">

<p><b>Other topics not covered in this year's version of the course:</b> Audiovisual data (Images, audio, and video as data.)</p>

<h4>Background reading</h4>
<ul>
<li><p>LeCun, Y., Bengio, Y., & Hinton, G. (2015). <a href="https://www.nature.com/nature/journal/v521/n7553/abs/nature14539.html">Deep learning</a>. <i>Nature</i>, 521(7553), 436-444.</p>
</li>
</ul>

<h4>Readings for discussion</h4>
<ul>
<li><p>Messing, S., Jabon, M., & Plaut, E. (2016). <a href="https://academic.oup.com/poq/article-lookup/doi/10.1093/poq/nfv046">Bias in the Flesh: Skin Complexion and Stereotype Consistency in Political Campaigns</a>. <i>Public Opinion Quarterly</i>, 80(1), 44–65.</p>
</li>
<li><p>Anastasopoulos, L. J., Badani, D., Lee, C., Ginosar, S., & Williams, J. (2017). Photographic home styles in Congress: a computer vision approach. Working paper, UC Berkeley. [see Blackboard for most recent version.]</p>
</li>
<li><p>Dietrich, B. (2017). <a href="https://polmeth.polisci.wisc.edu/Papers/dietrich_social_polarization_1.pdf">Social Polarization in the U.S. House of Representatives</a>. Working paper, University of Iowa.</p>
</li>
<li><p>Knox, D. and Lucas, C. (2017). <a href="http://christopherlucas.org/files/PDFs/sam.pdf">A General Approach to Classifying Mode of Speech: The Speaker-Affect Model for Audio Data</a>. Working paper, MIT.</p>
</li>
</ul>

<p><b>Other topics not covered in this year's version of the course:</b> Spatial data. Geographical Information Systems (GIS). Spatial autocorrelation. Spatial autoregresion models.</p>

<p><a href="slides/14-GIS.pdf">SLIDES (.pdf): GIS.</a></p>


<h4>Background reading</h4>
<ul>
<li><p>Gleditsch, K. S., & Weidmann, N. B. (2012). <a href="http://www.annualreviews.org/doi/full/10.1146/annurev-polisci-031710-112604">Richardson in the information age: Geographic information systems and spatial data in international studies.</a> <i>Annual Review of Political Science</i>, 15, 461-481.</p>
</li>
<li>Chapters 1 and 2 of Ward, M. D., & Gleditsch, K. S. (2008). <a href="http://usc.summon.serialssolutions.com/#!/search?bookMark=ePnHCXMw42JgAfZbU5mhpykZguaRDEEzZ1ygUTEDY3NL0E2kohrhicGpwcGa0CLTBHSOmikHbHAEyudkkARdzAuMCIWi1HTIutA8BfAVMcXcDFJuriHOHrqlxcnx0KGOeNA2TyND0JGeeCQBL9kqOg">Spatial regression models.</a> Sage.
</ul>

<h4>Readings for discussion</h4>
<ul>
<li><p>Weidmann, N. B. (2009). <a href="http://journals.sagepub.com/doi/abs/10.1177/0022002709336456">Geography as motivation and opportunity: Group concentration and ethnic conflict.</a> <i>Journal of Conflict Resolution</i>, 53(4), 526-543.</p>
</li>
<li><p>Montgomery, J. M., & Nyhan, B. (2017). <a href="http://www.journals.uchicago.edu/doi/abs/10.1086/690301">The Effects of Congressional Staff Networks in the US House of Representatives</a>. <i>The Journal of Politics</i>, 79(3), 745-761.</p></li>
</ul>


</div>
</div>
</div>